language: node_js

node_js:
  - "8"
  - "6"

cache: yarn

before_install:
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update
  - yarn run lint

script:
  - yarn test:cover
  - yarn danger

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - yarn run test:cover:CI
